# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "flyingcircus/nixos-14.12-i686"
  config.vm.network "private_network", ip: "192.168.50.4"
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
  end

  config.vm.provision :nixos, :verbose => true, :path => "provision.nix"
  config.vm.synced_folder "../../", "/opt/batou", :mount_options => ["dmode=777","fmode=666"]
end
