from typing import Literal, override

from batou.component import Component

def ensure_empty_directory(path: str) -> None: ...
def exactly_one(
    *args: object,
) -> bool: ...

class Clone(Component):
    namevar: Literal["url"]
    url: str
    target: str
    revision: str | None
    branch: str | None
    tag: str | None
    vcs_update: bool
    clobber: bool
    _force_clone: bool

    def __init__(
        self,
        url: str | None = ...,
        *,
        target: str = ...,
        revision: str | None = ...,
        branch: str | None = ...,
        tag: str | None = ...,
        vcs_update: bool = ...,
        clobber: bool = ...,
    ) -> None: ...
    @override
    def configure(self) -> None: ...
    def current_branch(self) -> str: ...
    def current_revision(self) -> str: ...
    def current_tag(self) -> str | None: ...
    def has_changes(self) -> bool: ...
    def has_incoming_changesets(self) -> str: ...
    def has_outgoing_changesets(self) -> bool: ...
    def last_updated(self) -> float | None: ...
    def remote_url(self) -> str: ...
    def untracked_files(self) -> list[str]: ...
    @override
    def update(self) -> None: ...
    @override
    def verify(self) -> None: ...
