import re
from typing import Literal, override

from batou.component import Component

class Clone(Component):
    namevar: Literal["url"]
    url: str
    target: str
    revision: str | None
    branch: str | None
    vcs_update: bool
    _revision_pattern: re.Pattern[str]

    def __init__(
        self,
        url: str | None = ...,
        *,
        target: str = ...,
        revision: str | None = ...,
        branch: str | None = ...,
        vcs_update: bool = ...,
    ) -> None: ...
    @override
    def configure(self) -> None: ...
    def current_branch(self) -> str: ...
    def current_revision(self, long: bool = ...) -> str | None: ...
    def has_changes(self) -> bool: ...
    def has_incoming_changesets(self) -> bool: ...
    def has_outgoing_changesets(self) -> bool: ...
    def last_updated(self) -> float | None: ...
    @property
    def revision_or_branch(self) -> str: ...
    def untracked_files(self) -> list[str]: ...
    @override
    def update(self) -> None: ...
    @override
    def verify(self) -> None: ...
