#!/bin/sh
{	# prevent execution of partial downloads.
set -e

oops() {
    echo "$0:" "$@" >&2
    exit 1
}

curl -sL https://raw.githubusercontent.com/flyingcircusio/batou/master/appenv.py -o appenv || oops "failed to download appenv"
chmod +x appenv
ln -sf appenv batou
echo "batou>=2.3b3" >> requirements.txt
sed -e 's!.*batou_ext.*!batou_ext @ https://github.com/flyingcircusio/batou_ext/archive/f2d1ce75a15eeaf4701686bb64e6616c5c35e31c.zip#sha256=4242d65a4cb0721812a308d2cfa87d647ba78f3e03ae4d189f9d2ac78157df93!' requirements.txt > requirements.txt.new
mv requirements.txt.new requirements.txt
./appenv update-lockfile
./batou migrate --bootstrap
./batou --help
if [ -d ".git" ]; then
	echo '.appenv' >> .gitignore
	git add .gitignore requirements.txt requirements.lock batou appenv
fi
}
