#!/bin/bash
set -ex

# Prepare additional Python verisons

if [ ! -e bin/buildout ]; then
    virtualenv .
    bin/python bootstrap.py
fi
bin/buildout
cd ..

pip install setuptools==18.3.1 --use-mirrors
pip install zc.buildout==2.4.3 --use-mirrors
pip install virtualenv==13.0.3 --use-mirrors

buildout

bin/py.test -m '1'
