#!/bin/bash
set -ex

# Prepare additional Python verions

if [ ! -e "buildout.python" ]; then
    git clone https://github.com/collective/buildout.python.git
fi
cd buildout.python
git checkout --force
if [ ! -e bin/buildout ]; then
    virtualenv .
    bin/python bootstrap.py
fi
bin/buildout
cd ..

pip install setuptools==18.3.1 --use-mirrors
pip install zc.buildout==2.4.3 --use-mirrors
pip install virtualenv==13.0.3 --use-mirrors

buildout

export PATH="$PATH:buildout.python/python-buildout.python/python-3.5/bin/python3.5"
export PATH="$PATH:buildout.python/python-buildout.python/python-3.4/bin/python3.4"
bin/py.test -m '1'
