from typing import Self

from batou.host import Host

def bool_arg(arg: str, state: bool) -> str: ...

class FCDevVM:
    target_host: str | None
    aliases: tuple[str, ...]
    memory: str | None
    cores: str | None
    disk_size: str | None
    hydra_eval: str
    channel_url: str
    update_channel: bool
    image_url: str
    SEED_TEMPLATE: str

    def __init__(self, name: str) -> None: ...
    @classmethod
    def from_config_section(cls, name: str, section: dict[str, str]) -> FCDevVM: ...
    def configure_host(self, host: Host, config: dict[str, str]) -> None: ...
    def provision(self, host: Host) -> None: ...
    def suggest_name(self, name: str) -> str: ...
    def summarize(self, host: Host) -> None: ...

class Provisioner:
    name: str
    rebuild: bool

    def __init__(self, name: str) -> None: ...
    @classmethod
    def from_config_section(cls, section: dict[str, str]) -> Self: ...
    def provision(self, host: Host) -> None: ...
    def suggest_name(self, name: str) -> str: ...
