from types import TracebackType
from typing import Any

from batou._output import OutputBackend
from batou.environment import Environment

deployment: Deployment | None
environment: Environment
target_directory: str
deployment_base: str
channel: object | None  # execnet channel, set at runtime by remote_exec
git_origin: str

def _hg_current_id() -> str: ...
def build_batou() -> None: ...
def cmd(c: str, acceptable_returncodes: list[int] = ...) -> tuple[bytes, bytes]: ...
def deploy(root: str, predict_only: bool = ...) -> None: ...
def ensure_base(base: str) -> str: ...
def ensure_repository(target: str, method: str) -> str: ...
def git_current_head() -> str | None: ...
def git_pull_code(upstream: str, branch: str) -> None: ...
def git_unbundle_code() -> None: ...
def git_update_working_copy(branch: str) -> str: ...
def hg_current_heads() -> list[str]: ...
def hg_pull_code(upstream: str) -> None: ...
def hg_unbundle_code() -> None: ...
def hg_update_working_copy(branch: str) -> str: ...
def lock() -> str: ...
def root_dependencies() -> dict[
    tuple[str, str],
    dict[str, Any],
]: ...  # Any: dependency data heterogeneous
def setup_deployment(*args: object) -> bytes: ...
def setup_output(debug: bool) -> None: ...
def whoami() -> str: ...

class CmdError(Exception):
    cmd: str
    returncode: int
    stdout: bytes
    stderr: bytes

    def __init__(self, cmd: str, returncode: int, stdout: bytes, stderr: bytes) -> None: ...
    def report(self) -> str: ...

class Deployment:
    env_name: str
    host_name: str
    overrides: dict[str, Any]  # Any: override values heterogeneous
    resolve_override: dict[str, str]
    resolve_v6_override: dict[str, str]
    host_data: dict[str, dict[str, Any]]  # Any: host data heterogeneous
    secret_files: dict[str, str] | None
    secret_data: set[str] | None
    timeout: int | None
    platform: str | None
    os_env: dict[str, str]
    environment: Environment | None

    def __init__(
        self,
        env_name: str,
        host_name: str,
        overrides: dict[str, Any],  # Any: override values heterogeneous
        resolve_override: dict[str, str],
        resolve_v6_override: dict[str, str],
        secret_files: dict[str, str] | None,
        secret_data: set[str] | None,
        host_data: dict[str, dict[str, Any]],  # Any: host data heterogeneous
        timeout: int | None,
        platform: str | None,
        os_env: dict[str, str] | None = ...,
    ) -> None: ...
    def deploy(self, root: str, predict_only: bool) -> None: ...
    def load(self) -> list[Any]: ...  # Any: loaded component data heterogeneous

class Output:
    enable_debug: bool
    backend: OutputBackend
    _buffer: list[tuple[str, tuple[object, ...], dict[str, object]]]
    _flushing: bool

    def __init__(self, backend: OutputBackend) -> None: ...
    def annotate(self, message: str, debug: bool = ..., icon: bool | str = ..., **fmt: object) -> None: ...
    def buffer(self, cmd: str, *args: object, **kw: object) -> None: ...
    def clear_buffer(self) -> None: ...
    def error(
        self,
        message: str,
        exc_info: tuple[
            type[BaseException] | None,
            BaseException | None,
            TracebackType | None,
        ]
        | None = ...,
        debug: bool = ...,
    ) -> None: ...
    def flush_buffer(self) -> None: ...
    def line(self, message: str, debug: bool = ..., icon: bool | str | None = ..., **fmt: object) -> None: ...
    def section(self, title: str, debug: bool = ..., **fmt: object) -> None: ...
    def sep(self, sep: str, title: str, **fmt: object) -> None: ...
    def step(self, context: str, message: str, debug: bool = ..., icon: bool | str | None = ..., **fmt: object) -> None: ...
    def tabular(self, key: str, value: str, separator: str = ..., debug: bool = ..., **kw: object) -> None: ...
    def warn(self, message: str, debug: bool = ...) -> None: ...

class ChannelBackend:
    channel: Any  # Any: execnet channel

    def __init__(self, channel: Any) -> None: ...  # Any: execnet channel
    def _send(self, output_cmd: str, *args: object, **kw: object) -> None: ...
    def line(self, message: str, **fmt: object) -> None: ...
    def sep(self, sep: str, title: str, **fmt: object) -> None: ...
    def write(self, content: str, **fmt: object) -> None: ...
