# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.define "nixos" do |nixos|

    nixos.vm.box = "flyingcircus/nixos-15.09-x86_64"
    nixos.vm.network "private_network", ip: "192.168.51.5"
    nixos.vm.provider "virtualbox" do |v|
      v.memory = 1024
    end

    nixos.vm.provision :shell, \
      :inline => "
      nix-channel --update", \
      :run => "always"
    nixos.vm.provision :nixos, :verbose => true,\
      :path => "provision.nix", \
      :run => "always"

    nixos.vm.synced_folder "../../", "/opt/batou", :mount_options => ["dmode=777","fmode=666"]


  end

  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/trusty64"
    ubuntu.vm.network "private_network", ip: "192.168.51.6"
    ubuntu.vm.provider "virtualbox" do |v|
      v.memory = 1024
    end

    ubuntu.vm.provision :shell, \
      :inline => "
      apt-get update
      apt-get -y install python2.7 python-virtualenv
      ", \
      :run => "always"

    ubuntu.vm.synced_folder "../../", "/opt/batou", :mount_options => ["dmode=777","fmode=666"]

  end
end
