from collections.abc import Sequence
from pathlib import Path
from typing import Literal

from configupdater.configupdater import ConfigUpdater

from batou.environment import Environment
from batou.secrets.encryption import (
    AGEEncryptedFile,
    DiffableAGEEncryptedFile,
    EncryptedFile,
    GPGEncryptedFile,
)

def process_age_recipients(members: Sequence[str], environment_path: Path) -> tuple[list[str], bool]: ...

class AGESecretProvider:
    FileFactory: type[AGEEncryptedFile]
    secret_provider_str: str
    environment: Environment

    def __init__(self, environment: Environment) -> None: ...
    def _get_file(self, name: str, writeable: bool = ...) -> EncryptedFile: ...
    def _get_recipients_for_encryption(self) -> list[str]: ...
    def iter_secret_files(self, writeable: bool = ...) -> dict[str, EncryptedFile]: ...
    def write_config(self, content: bytes, force_reencrypt: bool = ...) -> None: ...

class ConfigFileSecretProvider:
    def _get_recipients(self) -> list[str]: ...
    @property
    def config(self) -> ConfigUpdater: ...
    def edit(self, edit_file: str | None = ...) -> GPGEncryptedFile | AGEEncryptedFile | DiffableAGEEncryptedFile: ...
    def iter_secret_files(self, writeable: bool = ...) -> dict[str, EncryptedFile]: ...
    def read(self) -> SecretBlob: ...
    def read_secret_files(self) -> dict[str, bytes]: ...
    def summary(self) -> None: ...
    def write_config_new(self, content: bytes) -> None: ...
    def write_file(self, file: EncryptedFile, content: bytes, reencrypt: bool = ...) -> None: ...
    def write_secret_files(self, secret_files: dict[str, bytes], reencrypt: bool = ...) -> None: ...
    def purge(self, except_files: dict[str, EncryptedFile] | None = ...) -> None: ...

class DiffableAGESecretProvider:
    FileFactory: type[DiffableAGEEncryptedFile]
    secret_provider_str: str
    environment: Environment

    def __init__(self, environment: Environment) -> None: ...

class GPGSecretProvider:
    secret_provider_str: str
    environment: Environment

    def __init__(self, environment: Environment) -> None: ...
    def _get_file(self, name: str, writeable: bool = ...) -> EncryptedFile: ...
    def _get_recipients_for_encryption(self) -> list[str]: ...
    def iter_secret_files(self, writeable: bool = ...) -> dict[str, EncryptedFile]: ...
    def write_config(self, content: bytes, force_reencrypt: bool = ...) -> None: ...

class NoSecretProvider:
    secret_provider_str: str
    environment: Environment

    def __init__(self, environment: Environment) -> None: ...
    def edit(self, edit_file: str | None = ...) -> EncryptedFile: ...
    def purge(self, except_files: dict[str, EncryptedFile] | None = ...) -> None: ...
    def read(self) -> SecretBlob: ...
    def read_secret_files(self) -> dict[str, bytes]: ...
    def write_config(self, content: bytes, force_reencrypt: bool = ...) -> None: ...
    def summary(self) -> None: ...

class SecretBlob:
    def __init__(
        self,
        host_data: dict[str, dict[str, str]],
        component_overrides: dict[str, dict[str, str]],
        secret_data: set[str],
        secret_files: dict[str, str],
    ) -> None: ...

class SecretProvider:
    secret_provider_str: Literal["gpg", "age", "age-diffable", "none"]
    environment: Environment

    def __init__(self, environment: Environment) -> None: ...
    @classmethod
    def from_environment(cls, environment: Environment) -> SecretProvider: ...
    @property
    def config(self) -> ConfigUpdater: ...
    def inject_secrets(self) -> None: ...
    def _get_recipients(self) -> list[str]: ...
    def read_secret_files(self) -> dict[str, bytes]: ...
    def write_config_new(self, content: bytes) -> None: ...
    def change_secret_provider(self, config: ConfigUpdater, old_secret_provider: SecretProvider) -> None: ...
    def purge(self, except_files: dict[str, EncryptedFile] | None = ...) -> None: ...
    def write_config(self, content: bytes, force_reencrypt: bool = ...) -> None: ...
    def edit(self, edit_file: str | None = ...) -> EncryptedFile: ...
    def read(self) -> SecretBlob: ...
    def summary(self) -> None: ...
    def write_file(self, file: EncryptedFile, content: bytes) -> None: ...
