import pathlib
import types
from typing import Self, TextIO

from configupdater.configupdater import ConfigUpdater

debug: bool
identities: list[str] | None
known_passphrases: dict[str, str]

class EncryptedFile:
    file_ending: str | None
    path: pathlib.Path
    writeable: bool
    fd: TextIO | None
    is_new: bool | None
    _decrypted: bytes | None

    def __init__(self, path: pathlib.Path, writeable: bool = ...) -> None: ...
    @property
    def decrypted(self) -> bytes: ...
    def decrypt(self) -> bytes: ...
    @property
    def cleartext(self) -> str: ...
    @property
    def locked(self) -> bool: ...
    def write(
        self,
        content: bytes,
        recipients: list[str],
        reencrypt: bool = ...,
    ) -> None: ...
    def _write(
        self,
        content: bytes,
        recipients: list[str],
        reencrypt: bool = ...,
    ) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        tb: types.TracebackType | None,
    ) -> bool | None: ...
    def _lock(self) -> None: ...
    def _unlock(self) -> None: ...
    @property
    def exists(self) -> bool: ...
    def delete(self) -> None: ...

class NoBackingEncryptedFile(EncryptedFile):
    def __init__(self) -> None: ...
    def decrypt(self) -> bytes: ...
    @property
    def locked(self) -> bool: ...
    def _lock(self) -> None: ...
    def _unlock(self) -> None: ...

class GPGEncryptedFile(EncryptedFile):
    file_ending: str
    _gpg: str | None
    GPG_BINARY_CANDIDATES: list[str]

    def decrypt(self) -> bytes: ...
    def _extract_recipients(self) -> list[str] | None: ...
    def _recipient_to_keyid(self, recipient: str) -> str | None: ...
    def _write(
        self,
        content: bytes,
        recipients: list[str],
        reencrypt: bool = ...,
    ) -> None: ...
    @classmethod
    def gpg(cls) -> str: ...

def expect(fd: int, expected: bytes) -> tuple[bool, bytes]: ...
def get_identities() -> list[str]: ...
def get_passphrase(identity: str) -> str: ...

class AGEEncryptedFile(EncryptedFile):
    file_ending: str
    _age: str | None
    AGE_BINARY_CANDIDATES: list[str]

    def decrypt(self) -> bytes: ...
    def _write(
        self,
        content: bytes,
        recipients: list[str],
        reencrypt: bool = ...,
    ) -> None: ...
    @classmethod
    def age(cls) -> str: ...

class DiffableAGEEncryptedFile(EncryptedFile):
    file_ending: str
    _decrypted_content: ConfigUpdater | None
    _encrypted_content: ConfigUpdater | None

    def __init__(self, path: pathlib.Path, writeable: bool = ...) -> None: ...
    def decrypt_age_string(self, content: str) -> str: ...
    def encrypt_age_string(self, content: str, recipients: list[str]) -> str: ...
    def decrypt(self) -> bytes: ...
    def _write(
        self,
        content: bytes,
        recipients: list[str],
        reencrypt: bool = ...,
    ) -> None: ...

all_encrypted_file_types: list[type[EncryptedFile]]

def get_encrypted_file(path: pathlib.Path, writeable: bool = ...) -> EncryptedFile: ...
