name: Unit tests

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Install age
        run: |
          sudo apt-get update
          sudo apt-get install -y age
          sudo apt-get install -y subversion

      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Show environment
        run: set

      - name: Test
        run: uv tool install tox --with tox-uv-bare --with tox-gh

      - run: tox -- -vv
