name: "Nix Test"

on:
  push:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - run: nix build
      - run: nix flake check
