name: pre-commit

on:
  push:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v7
      - run: uv tool install pre-commit --with pre-commit-uv --force-reinstall
      - run: pre-commit run --all-files
