from collections.abc import Callable
from pathlib import Path

def migrate(output: Callable[..., None]) -> None: ...
def _get_environment_names() -> list[Path]: ...
def _migrate_environment(name: str) -> None: ...
